### ISSUE TITLE
Fix "0ced039 - mgesmundo / fix-empty-mask" not working.

### ISSUE THREAD

**Issue by joaokrabbe** [KazanExpress/ke-the-mask#8]
Hi @kaskar2008.

The fix for empty mask is not working anymore. So I made a comment on commit [02490b8 - Update directive.js](https://github.com/KazanExpress/ke-the-mask/commit/02490b8d33419dfa24522e048606772c0edb85e4), which I think is causing the error. 

I applied the fix mentioned on comment to my base, and it worked for me.

I would be grateful if you can analyze this.

**Comment by kaskar2008** [comment]
Hello @joaokrabbe!

We are using the mask like this:

```ts
props: {
   mask: {
      type: [String, Array, Object],
      default: '',
   },
}
```

and the view is:

```pug
input(
  v-mask="mask"
  v-bind="$attrs"
  v-on="$listeners"
  :value="inputValue"
)
```

And this works pretty fine for a long time :)
I understand your concern but I couldn't reproduce the error.

Any reproduction link?

**Comment by kaskar2008** [comment]
Oh, I've just bumped into an error :0

I'm on it.

**Comment by kaskar2008** [comment]
Patched!

**Comment by kaskar2008** [comment]
> ...
> 
> and the view is:
> 
> ```pug
> input(
>   v-mask="mask"
>   v-bind="$attrs"
>   v-on="$listeners"
>   :value="inputValue"
> )
> ```
> ...

Actually I was wrong about the using of the the mask :)

The real usage was:

```pug
input(
  v-mask="{ mask }"   <- this line
  v-bind="$attrs"
  v-on="$listeners"
  :value="inputValue"
)
```

**Comment by joaokrabbe** [comment]
@kaskar2008 Thank you!
